# Configure main menu and social menu
#[[main]]
#identifier = "Home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true


[[social]]
identifier = "Mastodon"
name = "Mastodon"
url = "https://bgme.me/@HennZaiTennshou"

[social.params]
icon = "Mastodon"


[[social]]
identifier = "notion"
name = "notion"
url = "https://www.notion.so/f6c5ecd3439941c29f3e6a12f36e7c50?pvs=4"

[social.params]
icon = "Notion"

[[social]]
identifier = "RSS"
name = "RSS"
url = "/index.xml"

[social.params]
icon = "rss"