baseURL = 'https://harushuura.vip'
DefaultContentLanguage = "zh"
languageCode = 'zh-cn'
title = '春天与阿修罗'
copyright = "春天与阿修罗 谢绝无断转载分发 since01/03/2024"
theme = 'diary'
hasCJKLanguage = true

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "perldoc"
    tabWidth = 4
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true


[params]
subtitle = "食宇宙尘埃·或吐纳着空气和盐水"

# 评论功能
enableTwikoo = true
twikooEnvId = "https://comment.harushuura.vip/"


enableimgloop = true
customCSS = ["//assets/scss/custom.scss"]






[[menu.main]]
url = "/tags"
name = "Tags｜标签"
weight = 6




